version: '3'
services:
  login_app:
    image: python:3.6.8-alpine
    environment:
      - LOGIN_NAME=${login_name}
      - PASSWORD=${password}
    volumes:
      - ./app/:/var/app
    command: ["python", "/var/app/login.py"]
